### ISSUE TITLE
guidance on configuration for enabling map view.

### ISSUE THREAD

**Issue by fils** [ad-freiburg/qlever-ui#131]
I've followed the guidance at:  https://github.com/ad-freiburg/qlever-ui/blob/master/docs/configure_qleverui.md

I've been able to do geosparql calls and have the correct WKT Litteral as last column in the return.

For example

```sparql
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
SELECT ?b ?left_geometry ?has_geometry  WHERE {
  <http://portal.medin.org.uk/portal/json-ld/039b8bff-9a49-49b8-85b7-12cb23f0fc64.jsonld> geo:hasCentroid/geo:asWKT ?left_geometry .
  ?left_geometry <max-distance-in-meters:5000> ?has_geometry .
  ?b geo:hasCentroid/geo:asWKT ?has_geometry .
}
```

works. 

I also can compile and run https://github.com/ad-freiburg/qlever-petrimaps and can confirm it is running via curl.

However, I don't see the map option in the qlever-ui when doing a query that returns the type and location in column order.

I think this is likely due to not knowing what the values in the configuration are that I need to pass.   I have tried adding

```
[mapview]
ENABLE_MAP_VIEW     = true
MAP_VIEW_BASE_URL  = http://workstation.lan:9090
```

based on inspecting the code a bit, but still no luck.

Just curious if an example configuration for referencing a local instance of perimaps could be provided.

Thanks
Doug

**Comment by Qup42** [comment]
The conditions for the map view being shown are that the last column is a geometry (seems to the case for your query) and that a map view server (empty by default) is configured for that back end. The map view server cannot yet be set through qlever-control, though that should be possible once ad-freiburg/qlever-control#141 is merged. For now you can also set it in the Django backend.
- go to `/admin/backend/backend/` and select the your backend (`Default` or the value of `UI_CONFIG` if set in your Qleverfile)
- set `Map view base URL` to the location of your petrimaps instance (here `http://workstation.lan:9090`) and `SAVE` at the bottom of the page

The map view button should now be shown when the last column contains geometries.

**Comment by hannahbast** [comment]
@fils We just committed https://github.com/ad-freiburg/qlever-control/commit/5018be5b53681ea84a10e3ba65d5c938aa782314 . Please have a look and let us know whether that solves your problem

**Comment by fils** [comment]
@hannahbast is there any guidance on what the Qleverfile-ui.yml file should look like?

If I follow, I need to make this file to override the default on in the container.   I did that but didn't know what to put in it, so I just did 

```yaml
---
ENABLE_MAP_VIEW     = true
MAP_VIEW_BASE_URL  = http://localhost:9090
```

I get the error 

```bash
(qleverflow) ➜  local git:(qlever) ✗ qlever --qleverfile Qleverfile-local ui  --host-name workstation.lan

To enable autocompletion, run the following command, and consider adding it to your `.bashrc` or `.zshrc`:

eval "$(register-python-argcomplete qlever)" && export QLEVER_ARGCOMPLETE_ENABLED=1


Command: ui

docker pull -q docker.io/adfreiburg/qlever-ui
docker run -d --volume $(pwd):/app/db --env QLEVERUI_DATABASE_URL=sqlite:////app/db/local.ui-db.sqlite3 --publish 8176:7000 --name qlever.ui.local docker.io/adfreiburg/qlever-ui
docker exec -i qlever.ui.local bash -c "python manage.py config local /app/db/Qleverfile-ui.yml --hide-all-other-backends"

Found config file `Qleverfile-ui.yml` and reusing it
Failed to configure the QLever UI (CommandError: Backend matching query does not exist.)
```

This seems to come from line 72 in config.py in qlever-ui

```
backend/management/commands/config.py
72:            raise CommandError(f"Backend `{backend_slug}` does not exist")
```

I have petrimaps running and qlever working fine, but still get this odd error in running the UI.   Note I am using 
qlever-control to run this.  

Appreciate the ping on this...
I saw the previous note about long WKTs too, so I am going to circle back now and try and load Marine Regions again! 

Thanks
Doug

**Comment by hannahbast** [comment]
@fils You don't have to write your own `Qleverfile-ui.yml`. The `qlever ui` command will create one for you and then you can edit it. Here is how they look like in principle: https://qlever.cs.uni-freiburg.de/api/config/wikidata . You can replace `wikidata` by any of the available slugs from https://qlever.cs.uni-freiburg.de . Please try the following:

1. Make sure you have the latest version of the `qlever` CLI, which is 0.5.23
2. In the `[ui]` section of your Qleverfile, define `UI_CONFIG = default`
3. In the directory with your qlever index, remove any leftover files `*.ui-db.sqlite3` and `Qleverfile-ui.yml` from your previous attempts
4. Run `qlever ui` again
5. See if you get a proper `Qleverfile-ui.yml` now

What I realized in the meantime: The image for the QLever UI provides a number of configurations. The mechanism I just described does not yet work properly when your `UI_CONFIG` has a value that is not amount these configurations. But it should work for `UI_CONFIG = default`. It should also work for `UI_CONFIG = wikidata` or `UI_CONFIG = imdb`, etc.

**Comment by hannahbast** [comment]
@fils Sounds good, thanks for the feedback. Yes, `qlever-petrimaps` has a Docker image, but compiling from source should also be easy if you are on a standard Linux OS. And yes, you should definitely update to the latest version (which is from mid April). There have been several important changes, in particular regarding standard-compliant parsing of WKT literals and how `POINT`s are represented and processed.

Petrimaps can handle all the standard 2D geometries: `POINT`, `LINESTRING`, `POLYGON`, `MULTIPOINT`, `MULTILINESTRING`, `MULTIPOLYGON`, `GEOMETRYCOLLECTION`.

Feel free to open an issue over at https://github.com/ad-freiburg/qlever-petrimaps when you encounter any problem.

We are working on bundling all these tools together even better. The new `qlever ui` mechanism was a first step in that direction.

**Comment by fils** [comment]
@hannahbast    I pulled the petrimaps docker and tried it with some other sample RDF that uses the GeoSPARQL properties and it worked with the new approach you provided!  So I'm looking good. 

 I have some more questions but I'll put them into a new issue this week, as it's really a tangent from this topic.  It's more related to deployment approaches in Docker and trying to learn what best practices are there.  

So I think the issue with the mapping above is some of the design choices that Marine Regions made in their RDF?  I hope later this week I can get some time to generate some new triples aligned with GeoSPARQL and see if I can get their data to render.  If so I have some connections to them and hope I can get them to align to, IMHO, some better types and properties.  DCAT centroid?  really?  ;)

**Comment by hannahbast** [comment]
@fils If the objects of the dcat:centroid predicate are WKT literals, it shouldn't matter what the name of the predicate is. Are they WKT literals? If you send me a link to your dataset or a part of it, I can check for myself what is going on.

**Comment by hannahbast** [comment]
@fils A very easy fix would be to just remove these prefixes when feeding the input to QLever. For example, in your Qleverfile, you could write something like this:

```
CAT_INPUT_FILES = cat <whatever> | sed 's/^"<[^>]\+> *POINT/POINT/'
```

And similarly if you use `MULTI_INPUT_JSON`.

I am using such fixes a lot when something is slightly wrong with the data or not how I like it. The fact that you can just pipe the data into QLever makes this very easy. Which is exactly why we designed it that way.

**Comment by fils** [comment]
@hannahbast yeah..     I just did a sed on the files and removed it.  And then it worked, results below.

Thanks  much!   The large WKT strings are loading fine and I can get the queries to map.    Really feeling good about all this.  Appreciate your support!  

The marine regions data is really nice.   I'll be showing this Tuesday to Deep Ocean Observing System (DOOS) group PI.  Will look forward to what she has to say about all this.  

![Image](https://github.com/user-attachments/assets/e3d034ba-ae4e-4bc4-9b8c-ce1684ec9d5f)
![Image](https://github.com/user-attachments/assets/9a0882e8-9fb0-4ca2-946e-90ab43bd6b32)
